# This is a basic workflow that is manually triggered

name: Create Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
      - run: sudo apt-add-repository https://cli.github.com/packages
      - run: sudo apt update
      - run: sudo apt install gh
      - run: npm install
      - run: npm run generate-key
      - run: node ./bin/update-version.js do ${{ github.event.inputs.version }}
      - run: |
          git add ./src/manifest.json
          git commit -m "chore: updating version to ${{ github.event.inputs.version }}"
      - run: npm run build
      - run: echo ${{ secrets.GH_ACCESS_TOKEN }} | gh auth login --with-token
      - run: gh release create ${{ github.event.inputs.version }}
